### PR TITLE
Reap leftover zombie processes

### LINKED ISSUE #33: Sio2jail leaves zombie processes
This can be observed (seems like at least on master and all sandboxed releases from 1.1.0 above) by:
1. Compiling a simple executable, like ``main(){}``
2. Adding sth like this:
```diff --git a/src/sio2jail.cc b/src/sio2jail.cc
--- a/src/sio2jail.cc
+++ b/src/sio2jail.cc
@@ -2,10 +2,14 @@
 #include "s2japp/Application.h"
 
 #include <iostream>
+#include <sys/wait.h>
 
 int main(int argc, const char* argv[]) {
     try {
-        return s2j::app::Application(argc, argv).main();
+        int ret = s2j::app::Application(argc, argv).main();
+        while (wait(NULL)>0)
+            std::cerr << "bruh";
+        return ret;
     }
     catch (const std::exception& ex) {
         std::cerr << "Exception occurred: " << ex.what() << std::endl;
```
4. Building and running sio2jail with arbitrary (?) args, for example ``--mount-namespace off ~/a``; adding ``-t 1`` gives the same result
5. Witnessing the bruh

Alternatively, one can add sleep(100) before the while and check htop or sth of this nature.

One way to fix this is executing the ``while`` from above silently, though that may be more of a workaround than an actual solution.

### PR DESCRIPTION
**Pull request by otargowski**
Resolves https://github.com/sio2project/sio2jail/issues/33.

We don't have to use the more complex ``waitid()``, as the child is sure to have exited already.

### CODE REVIEW

File: src/executor/Executor.cc [hunk 1]
```diff
@@ -190,6 +190,11 @@ void Executor::executeParent() {
     for (auto& listener: eventListeners_) {
         listener->onPostExecute();
     }
+    // This is needed, as most earlier waits have the WNOWAIT flag.
+    if (waitpid(-1, NULL, WNOHANG) == -1 && errno != ECHILD) {
+        throw SystemException(
+                std::string("final waitpid failed: ") + strerror(errno));
+    }
```
Comment (Wolf480pl) [inline src/executor/Executor.cc]: I think this could be ~~simplified~~ DRY-d by using [withErrnoCheck(description, ignoredErrnos, func, args...)](https://github.com/sio2project/sio2jail/blob/c1a8669b7c03c1aeda54d5757598371bafc0d150/src/common/WithErrnoCheck.h#L93-L97)

Like this:
```
withErrnoCheck("final waitpid", {ECHILD}, waitpid, -1, NULL, WNOHANG)
```
That'd be more consistent with [other code](https://github.com/sio2project/sio2jail/blob/c1a8669b7c03c1aeda54d5757598371bafc0d150/src/tracer/TraceExecutor.cc#L73-L80).

Unless you find `withErrnoCheck` confusing, then we can merge this as is.

**Review by Wolf480pl — APPROVED** [review]
